"""
Reduced three-state model of strain-class dynamics.
Tests whether the geometric class structure (C_small / C_free / C_large)
generates anomalous scaling of structure functions (multifractal intermittency).

Run: python3 three_state_model.py   (requires numpy, scipy)
"""
import numpy as np
from scipy.stats import kurtosis

def run(seed=1, T=500000, dt=0.005, three_state=True, reg='tanh'):
    rng = np.random.default_rng(seed)
    if three_state:
        states = ['small', 'free', 'large']
        a = {'small': 0.6, 'free': -0.4, 'large': -0.15}      # drift per class
        noise = {'small': 0.25, 'free': 0.4, 'large': 0.25}
        # transition matrix; C_free acts as transitional hub
        Pm = np.array([[0.97, 0.025, 0.005],
                       [0.05, 0.92, 0.03],
                       [0.015, 0.04, 0.945]])
        si = 1
    else:
        states = ['single']; a = {'single': 0.0}; noise = {'single': 0.35}; si = 0
    logg = 0.0; G = []
    for _ in range(T):
        st = states[si]
        logg += a[st] * dt + noise[st] * np.sqrt(dt) * rng.standard_normal()
        if reg == 'tanh':
            logg = np.tanh(logg / 4) * 4        # soft regularization (viscous analogue)
        G.append(np.exp(logg))
        if three_state:
            si = rng.choice(3, p=Pm[si])
    return np.array(G)

def scaling_exponents(G, lags=(2, 4, 8, 16, 32, 64), ps=(1, 2, 3, 4, 5, 6)):
    zeta = {}
    for p in ps:
        Sp = np.array([np.mean(np.abs(G[t:] - G[:-t]) ** p) for t in lags])
        zeta[p] = np.polyfit(np.log(lags), np.log(Sp + 1e-12), 1)[0]
    return zeta

if __name__ == '__main__':
    print("Three-state strain-class model: anomalous scaling test")
    print("=" * 60)
    G = run(three_state=True)
    z = scaling_exponents(G)
    print("Structure-function exponents zeta_p (K41 would give p/3):")
    for p in (1, 2, 3, 4, 5, 6):
        print(f"  p={p}: zeta_{p}={z[p]:.3f}   (K41: {p/3:.3f})")
    anomaly = z[6] - 2 * z[3]
    print(f"\nAnomaly indicator zeta_6 - 2*zeta_3 = {anomaly:.3f}")
    print("  (= 0 for K41, < 0 for multifractal intermittency)")

    # control: single state must give ~0 (Gaussian, no anomaly)
    Gc = run(three_state=False)
    zc = scaling_exponents(Gc)
    print(f"\nControl (single state): zeta_6 - 2*zeta_3 = {zc[6] - 2*zc[3]:.3f}  (expected ~0)")

    print("\nConclusion: the anomaly is generated by the three-class structure.")
